fix partial sysstat dependency installations

diff --git a/load-generator/bin/start-agent b/load-generator/bin/start-agent
--- a/load-generator/bin/start-agent
+++ b/load-generator/bin/start-agent
@@ -4,6 +4,8 @@ set -o errexit
 set -o pipefail
 set -o nounset
 
+source bin/set-env-vars
+
 help_msg=$(cat <<EOF
 Runs the NFM agent
 Usage: $0 <TPS-dir> <region> [flamegraph]
@@ -14,8 +16,7 @@ EOF
 )
 
 if [[ $# -lt 2 || "$1" == "--help" || "$1" == "-h" ]]; then
-    echo "Error: missing required arguments, you have sent" "$@"
-    echo "$help_msg"
+    log "Error: missing required arguments, you have sent" "$@" "help: $help_msg"
     exit 0
 fi
 
@@ -31,8 +32,7 @@ then
         inst_type=`ec2-metadata -t | awk '{print $2}'`
         cmd_prefix="flamegraph -v -o results/${tps_dir}/flamegraph-${inst_type}-${tps_dir}-`date +%Y-%m-%dT%H:%M:%S`.svg --"
     else
-        echo "Error: flamegraph argument is wrong, you have sent" "$@"
-        echo "$help_msg"
+        log "Error: missing required arguments, you have sent" "$@" "help: $help_msg"
         exit 0
     fi
 fi
@@ -40,20 +40,17 @@ fi
 [ -d nfm_agent_temp_test_cgroup ] || sudo mkdir nfm_agent_temp_test_cgroup
 mountpoint -q nfm_agent_temp_test_cgroup || sudo mount -t cgroup2 none nfm_agent_temp_test_cgroup
 
-echo "Starting network-flow-monitor-agent"
+log "${GREEN}Starting network-flow-monitor-agent ${NC}"
 log_file="results/$tps_dir/`date +%Y-%m-%dT%H:%M:%S`-agent"
 
-# Check if the binary can run (there can be a GLIBC compatibility issue depending obn where the binary is built)
-if ! /usr/local/sbin/network-flow-monitor-agent --help >/dev/null 2>&1; then
-    echo "ERROR: network-flow-monitor-agent binary is incompatible with this system" | tee "$log_file"
-    echo "GLIBC version check:" | tee -a "$log_file"
-    ldd /usr/local/sbin/network-flow-monitor-agent 2>&1 | tee -a "$log_file"
+# Check if the binary can run (there can be a GLIBC compatibility issue depending on where the binary is built)
+if ! sudo $cmd_prefix /usr/local/sbin/network-flow-monitor-agent --cgroup ./nfm_agent_temp_test_cgroup \
+    --publish-reports on --log-reports on --aggregate-msecs 500 --endpoint-region $region \
+    --endpoint https://networkflowmonitorreports.$region.api.aws/publish \
+    --publish-secs 30 --jitter-secs 0 > "$log_file" 2>&1; then
+    log "${RED}ERROR: Failed to start network-flow-monitor-agent. Agent output:${NC}"
+    cat "$log_file"
     exit 1
 fi
 
-sudo $cmd_prefix /usr/local/sbin/network-flow-monitor-agent --cgroup ./nfm_agent_temp_test_cgroup \
-    --publish-reports on --log-reports on --aggregate-msecs 500 --endpoint-region $region \
-    --endpoint https://networkflowmonitorreports.$region.api.aws/publish \
-    --publish-secs 30 --jitter-secs 0 > "$log_file" 2>&1
-
-echo "network-flow-monitor-agent started successfully."
+log "${GREEN}Stopped network-flow-monitor-agent.${NC}"
